### ISSUE TITLE
Error on creating tmp file

### ISSUE THREAD

**Issue by KrzysztofMadejski** [dominictarr/excel-stream#7]
Lib (or some dependency) assumes that `/home/<userdir>/tmp` directory exists. Otherwise following error occurs:

```
tream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open '/home/<username>/tmp/_1415470413656'
```

Shouldn't it write to `/tmp` by default?

**Comment by guumaster** [comment]
updating package `osenv` seems to fix this issue.
