### ISSUE TITLE
excel-stream converts strings to ints

### ISSUE THREAD

**Issue by jcoetzee** [dominictarr/excel-stream#8]
I have an excel spreadsheet that has a phone number column, I have set the format of the data to text as I am expecting it as a string (there are leading zeros). No matter what I try excel-stream still parses these into integers. I have tried putting them into international format with the leading '+', these are stripped out and the resulting value converted to int.

Is there something I'm doing wrong here?

**Comment by dominictarr** [comment]
I don't know, this module is only a wrapper and http://npm.im/j please post an issue on that repo.
