### ISSUE TITLE
empty value will be converted to 0 which is unexpected

### ISSUE THREAD

**Issue by chhaj5236** [dominictarr/excel-stream#9]
As the following codes show, isNaN("") equals false, _data[k.trim()] will get the value 0.
```javascript
_data[k.trim()] = isNaN(value) ? value : +value
```
should the result "" be more reasonable? i.e.:
```javascript
_data[k.trim()] = (value === "" || isNaN(value)) ? value : +value
```

**Comment by dominictarr** [comment]
this module is just a wrapper around [j](http:ghub.io/j) please post the issue there.
